// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketMetro.App.Persistencia;

namespace TicketMetro.App.Persistencia.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20220819052048_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TicketMetro.App.Dominio.Estacion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("latitud")
                        .HasColumnType("float");

                    b.Property<double>("longitud")
                        .HasColumnType("float");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Estaciones");
                });

            modelBuilder.Entity("TicketMetro.App.Dominio.Persona", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("TicketMetro.App.Dominio.Ticket", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("fecha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("objEstacionFinalID")
                        .HasColumnType("int");

                    b.Property<int?>("objEstacionInicialID")
                        .HasColumnType("int");

                    b.Property<int?>("objPerosnaID")
                        .HasColumnType("int");

                    b.Property<int>("precion")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("objEstacionFinalID");

                    b.HasIndex("objEstacionInicialID");

                    b.HasIndex("objPerosnaID");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("TicketMetro.App.Dominio.Ticket", b =>
                {
                    b.HasOne("TicketMetro.App.Dominio.Estacion", "objEstacionFinal")
                        .WithMany()
                        .HasForeignKey("objEstacionFinalID");

                    b.HasOne("TicketMetro.App.Dominio.Estacion", "objEstacionInicial")
                        .WithMany()
                        .HasForeignKey("objEstacionInicialID");

                    b.HasOne("TicketMetro.App.Dominio.Persona", "objPerosna")
                        .WithMany()
                        .HasForeignKey("objPerosnaID");

                    b.Navigation("objEstacionFinal");

                    b.Navigation("objEstacionInicial");

                    b.Navigation("objPerosna");
                });
#pragma warning restore 612, 618
        }
    }
}
